server:
  port: 8081
go_live:
  public:
    start_iso_datetime: 1995-06-30T11:11:11+02:00
    booking_code: Kaiser-Wilhelm-Koog
  staff:
    start_iso_datetime: 1995-06-29T11:11:11+02:00
    booking_code: Dithmarschen
    group: staff
security:
  cors:
    disable: false
  oidc:
    id_token_cookie_name: JWT
    access_token_cookie_name: AUTH
    admin_group: admin
    token_public_keys_PEM:
      - |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
        4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u
        +qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyeh
        kd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ
        0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdg
        cKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbc
        mwIDAQAB
        -----END PUBLIC KEY-----
