service:
  attendee_service_url: 'http://localhost:9091' # base url to attendee service - no trailing slash
  auth_service_url: 'http://localhost:4712' # base url to auth service - no trailing slash
  mail_service_url: 'http://localhost:9093' # base url to mail service - no trailing slash
  join_link_base_url: 'http://localhost:10000' # base url for join links, appends context location
  # the maximum size of room groups that attendees can form
  #
  # Should usually be set to the largest available room size, unless you have just one room that is much larger
  # than all the others, then it may make sense to limit the group size to more typical room sizes.
  max_group_size: 6
  # allowed flags for groups.
  #
  # Flag "public" means a group is visible to approved attendees, who can then request to join it. If you
  # do not allow this flag here, no public groups will be supported.
  group_flags:
    - public
  # allowed flags for rooms.
  #
  # This service does not react to the flags, but UIs and exports may rely on presence of certain flags to
  # function correctly.
  room_flags:
    - handicapped
    - final
server:
  port: 9094
  read_timeout_seconds: 30
  write_timeout_seconds: 30
  idle_timeout_seconds: 120
database:
  use: 'mysql' # or inmemory
  username: 'demouser'
  password: 'demopw' # can also leave blank and set REG_SECRET_DB_PASSWORD
  database: 'tcp(localhost:3306)/dbname'
  parameters:
    - 'charset=utf8mb4'
    - 'collation=utf8mb4_general_ci'
    - 'parseTime=True'
    - 'timeout=30s' # connection timeout
security:
  cors:
    disable: false
  fixed_token:
    api: 'put_secure_random_string_here_for_api_token' # can also leave unset and set REG_SECRET_API_TOKEN
  oidc:
    id_token_cookie_name: JWT
    access_token_cookie_name: AUTH
    admin_group: admin
    token_public_keys_PEM:
      - |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
        4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u
        +qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyeh
        kd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ
        0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdg
        cKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbc
        mwIDAQAB
        -----END PUBLIC KEY-----
logging:
  style: ecs # or plain
  severity: INFO
# this section is currently unused. It was used by the old email style hotel booking, see
# https://github.com/eurofurence/reg-hotel-booking
go_live:
  public:
    start_iso_datetime: 1995-06-30T11:11:11+02:00
    booking_code: Kaiser-Wilhelm-Koog
  staff:
    start_iso_datetime: 1995-06-29T11:11:11+02:00
    booking_code: Dithmarschen
    group: staff
